[tools]
hk = "latest"
pkl = "latest"

[env]
HK_MISE = 1

[hooks]
postinstall = [
  # Automatically install/update hooks when tools are installed
  { run = "hk install --mise" },
  { task = "pkl-download-packages-for-all" },
]
