[vars]
github_repo_id_cmd = "gh repo view --json id --jq '.id'"
# X-Github-Next-Global-ID:1 explanation:
# https://github.blog/developer-skills/github/exploring-github-cli-how-to-interact-with-githubs-graphql-api-endpoint/#basic-query-example
# https://docs.github.com/en/graphql/guides/migrating-graphql-global-node-ids
gh_graphql = "gh api graphql --header X-Github-Next-Global-ID:1"
gh_graphql_repo = "{{vars.gh_graphql}} --field sourceId=$({{vars.github_repo_id_cmd}})"

[tools]
hk = "latest"
pkl = "latest"
jq = "latest"

[env]
HK_MISE = 1

[hooks]
postinstall = [
  # Automatically install/update hooks when tools are installed
  { run = "hk install --mise" },
  { task = "pkl-download-packages-for-all" },
]

[tasks.pkl-download-packages]
# pkl-lsp automatically downloads imports through an LSP extension that some editors, like VSCode, can use.
# Some editors, like Helix, don't support that extension. However, they can use cached imports if they have been
# manually downloaded.
tools.jq = "latest"
description = "Manually download packages for pkl files."
usage = '''
  arg "<pkl-files>" help="pkl files" var=#true var_min=1
'''
run = [
  '''
  pkl analyze imports --format json "{{ usage.pkl_files|unique|join(sep='" "') }}" \
    | jq --raw-output '.imports | keys | .[]' \
    | grep --regexp '^package://' \
    | cut --fields 1 --delimiter '#' \
    | uniq \
    | xargs pkl download-package
  ''',
]

[tasks.pkl-download-packages-for-all]
tools.fd = "latest"
description = "Manually download packages for all pkl files in project directory."
vars.all_pkl_files = '''{{exec(command="fd --glob '*.pkl' " ~ config_root)}}'''
# Does not require open and close double quotes:
run = [
  { task = "pkl-download-packages", args = [
    '''{{vars.all_pkl_files|split(pat='\n')|join(sep='" "')}}''',
  ] },
]
