mutation($sourceId: ID!) {
  check_signed_commits: createRepositoryRuleset(
    input: {
      bypassActors: [],
      conditions: {
        refName: {
          exclude: [],
          include: ["~ALL"]
        }
      },
      enforcement: ACTIVE,
      name: "Check signed commits",
      rules: [{type: REQUIRED_SIGNATURES}],
      sourceId: $sourceId,
      target: BRANCH
    }
  ) {
    ruleset {
      id
      createdAt
    }
  }
}
